run_id: grid_v0
embeddings:
  - yolo11x-seg
  - dinov3
  - clip
  - dinov3-attention
targets:
  - seg_loss
  - cls_loss
  - obj_loss
preproc:
  - none
  - standard
feature_selection:
  - none
  - spearman-0.05
  - spearman-0.20
  - spearman-0.40
extractors:
  - name: PLS
    params: {n_components: 5}
  - name: PLS
    params: {n_components: 20}
  - name: KPCA
    params: {n_components: 5, kernel: rbf}
  - name: KPCA
    params: {n_components: 20, kernel: rbf}
  - name: TSNE
    params: {n_components: 2}
  - name: TSNE
    params: {n_components: 10, method: "exact"}
  - name: UMAP
    params: {
        n_components: 2,
        n_neighbors: 10,
    }
  - name: UMAP
    params: {
        n_components: 2,
        n_neighbors: 50,
    }
  - name: UMAP
    params: {
        n_components: 10,
        n_neighbors: 10,
    }
  - name: UMAP
    params: {
        n_components: 10,
        n_neighbors: 50,
    }
n_jobs: 16
seed: 12345
cecihome: ${CECIHOME}
