run_id: grid_v0
embeddings:
  - yolo11x-seg
  - dinov3
  - clip
  - dinov3-attention
targets:
  - cls_loss
  - seg_loss
preproc:
  - none
  - standard
feature_selection:
  - none
  - spearman-0.20
  - spearman-0.40
  - spearman-0.60
extractors:
  - name: PLS
    params: {n_components: 5}
  - name: PLS
    params: {n_components: 20}
  - name: KPCA
    params: {n_components: 5, kernel: rbf}
  - name: KPCA
    params: {n_components: 20, kernel: rbf}
  - name: TSNE
    params: {n_components: 2}
  - name: UMAP
    params: {n_components: 2}
n_jobs: 1
seed: 12345
cecihome: ${CECIHOME}
